<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Message Information</name>
   <tag></tag>
   <elementGuidId>d7e17251-14be-4fc5-a93b-cde9ce11d2d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='__xmlview103--detail-anchBar-__xmlview103--mainSection-anchor-BDI-content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__xmlview103--detail-anchBar-__xmlview103--mainSection-anchor-BDI-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Message Information&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>6d6907ab-7ea7-4ad8-afea-8b0679cfed5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview103--detail-anchBar-__xmlview103--mainSection-anchor-BDI-content</value>
      <webElementGuid>3a5a163b-56c8-4c54-86e8-fbdeb9557361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>31ddd52d-8be3-4321-bec8-12dac19c0ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Message Information</value>
      <webElementGuid>ec5ea87f-e812-4cf7-8dbb-c168e52e6e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview103--detail-anchBar-__xmlview103--mainSection-anchor-BDI-content&quot;)</value>
      <webElementGuid>6b82e1c6-1925-419f-974b-96e0250c7109</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='__xmlview103--detail-anchBar-__xmlview103--mainSection-anchor-BDI-content']</value>
      <webElementGuid>05dc07c3-ce1a-47f4-b7f6-b7bcced0b46f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='__xmlview103--detail-anchBar-__xmlview103--mainSection-anchor-content']/bdi</value>
      <webElementGuid>f09ced0d-059a-4925-8b76-d2ae19d09adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scroll left'])[1]/following::bdi[1]</value>
      <webElementGuid>4b275752-d355-46a4-b480-219828184f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expand Header'])[2]/following::bdi[1]</value>
      <webElementGuid>367a4b9f-e6d3-498b-a9fe-016f23443261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payload'])[2]/preceding::bdi[1]</value>
      <webElementGuid>e95973d2-c34a-4797-a8b3-69bb2c74daa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Menu'])[1]/preceding::bdi[2]</value>
      <webElementGuid>b4a12429-3c95-4639-b527-2d8d464fc540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/span/span/bdi</value>
      <webElementGuid>c5f3ec98-4bc9-4080-bdc9-1646c2e93adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = '__xmlview103--detail-anchBar-__xmlview103--mainSection-anchor-BDI-content' and (text() = 'Message Information' or . = 'Message Information')]</value>
      <webElementGuid>3b4477c0-1012-4325-a046-4917f33244cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
