<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Payload</name>
   <tag></tag>
   <elementGuidId>423f3479-b94a-4d54-8278-31e3be48f9d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='__xmlview103--detail-anchBar-__xmlview103--payloadSection-anchor-internalSplitBtn-textButton-BDI-content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__xmlview103--detail-anchBar-__xmlview103--payloadSection-anchor-internalSplitBtn-textButton-BDI-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Payload&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>981c9d9f-feb9-4df0-a790-d2f06d8311d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview103--detail-anchBar-__xmlview103--payloadSection-anchor-internalSplitBtn-textButton-BDI-content</value>
      <webElementGuid>8469964f-c785-46b3-b436-e83c60620284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>5050279e-6156-4c0b-801a-ea1f3116540a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payload</value>
      <webElementGuid>b3fb7a27-9dd6-49e7-95be-292923fca126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview103--detail-anchBar-__xmlview103--payloadSection-anchor-internalSplitBtn-textButton-BDI-content&quot;)</value>
      <webElementGuid>4a595ed1-550a-469e-8388-ab03b2d17243</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='__xmlview103--detail-anchBar-__xmlview103--payloadSection-anchor-internalSplitBtn-textButton-BDI-content']</value>
      <webElementGuid>9ae0590e-d5e2-49fb-8bab-587db563ae42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='__xmlview103--detail-anchBar-__xmlview103--payloadSection-anchor-internalSplitBtn-textButton-content']/bdi</value>
      <webElementGuid>8ebea789-1829-4b8a-ba0a-7bff3560796d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message Information'])[2]/following::bdi[1]</value>
      <webElementGuid>f66120e1-e2ff-4fa9-b862-e8346d98269c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scroll left'])[1]/following::bdi[2]</value>
      <webElementGuid>de7d8dc5-989f-4c1d-80ec-d35d77ebc1b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Menu'])[1]/preceding::bdi[1]</value>
      <webElementGuid>7c326519-d9d9-4d90-8cae-b0cb14a9ab37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activate item to go to section in page'])[1]/preceding::bdi[1]</value>
      <webElementGuid>f5061101-916a-4f96-9436-f9d5e02e9a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button/span/span/bdi</value>
      <webElementGuid>7a3c634b-eba1-414b-bd6b-d2653da32845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = '__xmlview103--detail-anchBar-__xmlview103--payloadSection-anchor-internalSplitBtn-textButton-BDI-content' and (text() = 'Payload' or . = 'Payload')]</value>
      <webElementGuid>775406c6-8da6-49c3-85d8-d9b1c5070f8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
