<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_StandardSelect ViewExpand Header</name>
   <tag></tag>
   <elementGuidId>91e84eb4-732c-49cc-a648-b367c3d413fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__title5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__title5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;StandardSelect ViewExpand Header&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4f20f87d-4583-4b94-9309-697fca08d0a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__title5</value>
      <webElementGuid>b05a6828-e90b-47f0-9a7c-f62299c66ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__title5</value>
      <webElementGuid>ab64301a-5f26-4301-be11-8dc8ea8c73c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapFDynamicPageTitle</value>
      <webElementGuid>ed502c06-bd78-4c6b-b0ad-ed839063969c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>StandardSelect ViewExpand Header</value>
      <webElementGuid>3b669481-3da0-4c9c-a2b8-0c83c563b4c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__title5&quot;)</value>
      <webElementGuid>d1067b4d-58a3-4839-be36-7cb920e2bc2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='__title5']</value>
      <webElementGuid>279d059f-319e-49e7-bcc7-1bfee49e84ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='__xmlview102--messageListPage-header']/div</value>
      <webElementGuid>4ffd9049-6313-4495-ab24-9530a4131e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drag apps here to create links.'])[8]/following::div[14]</value>
      <webElementGuid>d4ca01c7-939b-4332-831e-12570af9e7fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='License Usage Report'])[1]/following::div[23]</value>
      <webElementGuid>e4d09df6-dbbf-450a-aead-b2ed45a2cc08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/header/div</value>
      <webElementGuid>fd2fb6d3-2f8f-4b14-9222-117954f3d9ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '__title5' and (text() = 'StandardSelect ViewExpand Header' or . = 'StandardSelect ViewExpand Header')]</value>
      <webElementGuid>fca77441-ea6a-4430-87bc-c55cab40560d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
