<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Items (17655)Refresh TableRefresh Table_4f2628</name>
   <tag></tag>
   <elementGuidId>e22c4c46-6675-408e-9a26-f1567544f0a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__toolbar22']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__toolbar22</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=toolbar[name=&quot;Items (17655)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a05b2104-955e-4d21-9296-8e49479d59ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__toolbar22</value>
      <webElementGuid>f3e8cc7d-8043-400a-a64a-9aabf36448b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__toolbar22</value>
      <webElementGuid>a8b844c6-c745-4801-be27-18d97446f281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-fastnavgroup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>95e00cd8-ff37-4f42-a32b-5f3325d4feb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>toolbar</value>
      <webElementGuid>b898397a-082d-4825-b1bf-d8c99da3f2ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>__title6</value>
      <webElementGuid>cf884fc0-7b01-4c9b-ba79-d7f9babe62a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-roledescription</name>
      <type>Main</type>
      <value>Overflow Toolbar</value>
      <webElementGuid>d411b323-e0d2-4499-acba-9c02804adf13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMIBar sapMTBInactive sapMTB sapMTBNewFlex sapMTBStandard sapMTB-Transparent-CTX sapMOTB sapMListHdr sapMListHdrTBar sapMTBHeader-CTX</value>
      <webElementGuid>7286c4fd-ba7a-4d23-a435-763628ed4e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Items (17655)Refresh TableRefresh TableRetryRetry MessagesAuto Retry SettingsAuto Retry SettingsSet To InactiveSet messages to inactive so that they are removed from the listCheck Integration ConfigurationCheck if the integration configuration is complete and correct.Retention SettingsSet retention time for messages.Sort SettingsGroup SettingsTable Settings</value>
      <webElementGuid>12162b66-b2eb-4e34-9576-e5d049e2bb81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__toolbar22&quot;)</value>
      <webElementGuid>96c2fa31-2b6b-4662-bd25-c6c978637f98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='__toolbar22']</value>
      <webElementGuid>1333c43f-ca18-49f4-953f-5169c54228ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__xmlview102--masterList']/div</value>
      <webElementGuid>bbd027d5-52fe-4369-862c-b10ba4859dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pin Header'])[1]/following::div[4]</value>
      <webElementGuid>be5f11b1-8b3b-4017-b547-e2b7a2691423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collapse Header'])[1]/following::div[4]</value>
      <webElementGuid>fafae705-415f-44de-8ca4-bd2f5efdad16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/div[2]/div/div/div</value>
      <webElementGuid>7d92fcec-3f7c-4a40-bdae-e7696eed7d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '__toolbar22' and (text() = 'Items (17655)Refresh TableRefresh TableRetryRetry MessagesAuto Retry SettingsAuto Retry SettingsSet To InactiveSet messages to inactive so that they are removed from the listCheck Integration ConfigurationCheck if the integration configuration is complete and correct.Retention SettingsSet retention time for messages.Sort SettingsGroup SettingsTable Settings' or . = 'Items (17655)Refresh TableRefresh TableRetryRetry MessagesAuto Retry SettingsAuto Retry SettingsSet To InactiveSet messages to inactive so that they are removed from the listCheck Integration ConfigurationCheck if the integration configuration is complete and correct.Retention SettingsSet retention time for messages.Sort SettingsGroup SettingsTable Settings')]</value>
      <webElementGuid>13dffaf4-3662-401e-bb2c-4aba87e31e0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
