<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_julie.hostedelaware.pro</name>
   <tag></tag>
   <elementGuidId>e5ef6acf-a422-4a85-8c1d-769bdd7eb284</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__text232']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__text232</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Subsection&quot;i >> internal:text=&quot;julie.hoste@delaware.pro&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bd622790-c1d2-4e88-a522-75a58c06f773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__text232</value>
      <webElementGuid>5f1ef430-73ab-4e74-8625-a7ca72e5c3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__text232</value>
      <webElementGuid>825e5f56-d5ee-4446-93bc-314b1348d0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>86456df5-dcfc-49af-aa6f-4856ba0af339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapUiSelectable sapMTextBreakWord sapMTextMaxWidth</value>
      <webElementGuid>45c700db-fa9c-4c42-bc82-6cfca2cc0599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>julie.hoste@delaware.pro</value>
      <webElementGuid>a9d7c184-a4e5-4193-bba0-ddcf7de1632b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__text232&quot;)</value>
      <webElementGuid>97d171a9-1008-4501-8fff-164c77861f69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__text232']</value>
      <webElementGuid>33ebbe93-e7a8-459e-a1fa-b99ad88541e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__xmlview103--SimpleFormDisplayColumn_oneGroup234--__label17--FE']/div[2]/span</value>
      <webElementGuid>fefc07ad-6af0-4ac4-95d6-7bdb7ad68bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created By'])[53]/following::span[2]</value>
      <webElementGuid>c06fef3b-db70-49c7-802f-72860eacd504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='s4demo'])[1]/following::span[4]</value>
      <webElementGuid>604dec25-0a19-4742-abd7-1cbe54743b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created On'])[53]/preceding::span[1]</value>
      <webElementGuid>bcb7137b-7caa-4aa6-845a-378d78477206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mar 14, 2025, 3:05:35 PM'])[2]/preceding::span[4]</value>
      <webElementGuid>cad8ef0e-1f6d-42ed-8e02-6acbc4404248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[5]/div[2]/span</value>
      <webElementGuid>5b72e87c-b61f-4342-809a-1363949e21cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__text232' and (text() = 'julie.hoste@delaware.pro' or . = 'julie.hoste@delaware.pro')]</value>
      <webElementGuid>4bb95b05-44c1-498e-93f1-945172b61f6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
