<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Entry successfully validated_sapUiIconTitle</name>
   <tag></tag>
   <elementGuidId>48f3c8f1-1988-4cf8-9a14-1cad7acccf36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__item104-__clone147-imgNav']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__item104-__clone147-imgNav > span.sapUiIconTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Row . 2 of 51 . Has Details . Message Number Object Identifier 20250314140535333534952 . Message Type EWM Goods Receipt . Plant 1210 DDE - Plant . Identifier Object Identifier  1210/1003344/121/DDE-101-0500-2500/3344_00001/712345678000144363 . Created By julie.hoste@delaware.pro . Created On 14 Mar 2025 15:05:35  Mar 14, 2025, 3:05:35 PM . Last Updated On 14 Mar 2025 15:05:38  Mar 14, 2025, 3:05:38 PM . Overall Status Completed Entry successfully validated&quot;i >> internal:attr=[title=&quot;Navigation&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c4b12c8e-3848-4183-94cb-13861a049cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Navigation</value>
      <webElementGuid>ffa6200d-e627-47e1-a93f-03d622c4d2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>59b726bc-c984-487d-80af-4bd845c73670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIconTitle</value>
      <webElementGuid>e59a2795-4f48-435d-a7d6-ddef1d850f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__item104-__clone147-imgNav&quot;)/span[@class=&quot;sapUiIconTitle&quot;]</value>
      <webElementGuid>e683b11f-eb98-4e1a-add0-419ecb7d030a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='__item104-__clone147-imgNav']/span</value>
      <webElementGuid>f0112fc2-5bb4-4732-9d45-521927cf248b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/span/span</value>
      <webElementGuid>a13e58ea-b977-40f4-b40a-4c2ed6322c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Navigation']</value>
      <webElementGuid>3a420425-bd27-4b84-8b2e-41d7b19de751</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
