<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_julie.hostedelaware.pro</name>
   <tag></tag>
   <elementGuidId>6693436f-3e2f-4268-9ba5-196fe4d3e7a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='__item104-__clone147-cell7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__item104-__clone147-cell7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Row . 2 of 51 . Has Details . Message Number Object Identifier 20250314140535333534952 . Message Type EWM Goods Receipt . Plant 1210 DDE - Plant . Identifier Object Identifier  1210/1003344/121/DDE-101-0500-2500/3344_00001/712345678000144363 . Created By julie.hoste@delaware.pro . Created On 14 Mar 2025 15:05:35  Mar 14, 2025, 3:05:35 PM . Last Updated On 14 Mar 2025 15:05:38  Mar 14, 2025, 3:05:38 PM . Overall Status Completed Entry successfully validated&quot;i >> internal:role=gridcell[name=&quot;julie.hoste@delaware.pro&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>38706766-c7a8-4cf6-b655-9134cb5d5671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__item104-__clone147-cell7</value>
      <webElementGuid>b8660ed4-244a-4a95-b54b-ded7df22c5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>ccb4097b-a0ab-48ed-8212-78decbb38ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>970e31b3-4f9b-49ee-8ec4-9f596a421b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c0d60904-caa4-40ea-beab-fdd3ab3be8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-column</name>
      <type>Main</type>
      <value>__xmlview102--createdBy</value>
      <webElementGuid>47f45dd1-fa46-45e8-9f56-ff93bfb92962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMListTblCell sapMTblCellFocusable</value>
      <webElementGuid>997b99be-0ebd-4b70-966d-19e42351af2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>julie.hoste@delaware.pro</value>
      <webElementGuid>e9045939-e592-4a33-a341-2177922afa0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__item104-__clone147-cell7&quot;)</value>
      <webElementGuid>c5311da8-6021-47e4-9d47-7d9893db355a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='__item104-__clone147-cell7']</value>
      <webElementGuid>3e1172cf-1929-42e0-98a1-6baf6a7beb77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='__item104-__clone147']/td[7]</value>
      <webElementGuid>f17e2b4a-71f3-4d2a-90f1-7a99a8e2547f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Object Status'])[1]/following::td[2]</value>
      <webElementGuid>e605e3bf-65a2-4128-b7b4-a9ed3adfca7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DDE - Plant'])[1]/following::td[2]</value>
      <webElementGuid>292ff5aa-644d-4182-9167-5a52ad713bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mar 14, 2025, 3:05:35 PM'])[1]/preceding::td[1]</value>
      <webElementGuid>023e9ace-5932-46ce-a61c-0a5914b53625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]</value>
      <webElementGuid>eaaa54d1-ca96-44f6-bded-61e0625f2f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = '__item104-__clone147-cell7' and (text() = 'julie.hoste@delaware.pro' or . = 'julie.hoste@delaware.pro')]</value>
      <webElementGuid>4a20cd39-f777-4e62-a587-546cff507fcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
