<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Overall Status___item104-__clone147-ModeCell</name>
   <tag></tag>
   <elementGuidId>ffe81fd0-4887-4a98-9ecf-5a171f8815c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='__item104-__clone147-ModeCell']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__item104-__clone147-ModeCell</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Row . 2 of 51 . Has Details . Message Number Object Identifier 20250314140535333534952 . Message Type EWM Goods Receipt . Plant 1210 DDE - Plant . Identifier Object Identifier  1210/1003344/121/DDE-101-0500-2500/3344_00001/712345678000144363 . Created By julie.hoste@delaware.pro . Created On 14 Mar 2025 15:05:35  Mar 14, 2025, 3:05:35 PM . Last Updated On 14 Mar 2025 15:05:38  Mar 14, 2025, 3:05:38 PM . Overall Status Completed Entry successfully validated&quot;i >> internal:role=gridcell[name=&quot;Item Selection&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>096687f0-55a3-4120-b490-8f957f17ed17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__item104-__clone147-ModeCell</value>
      <webElementGuid>cdb93ad5-6a14-46b9-9654-34caf0c1917e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>5a9b886d-3e58-4e7e-ae81-06b959b64209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>523fbd61-abb9-4c9b-83eb-21e61e37d4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bf329cd8-1cee-4dbf-8ff3-a53fc65e0cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMListTblSelCol sapMTblCellFocusable</value>
      <webElementGuid>257c4a1f-d0c3-439d-948c-fce2b7cd0608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e411e1c4-0621-4b0f-a3c0-e6b2959fc968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__item104-__clone147-ModeCell&quot;)</value>
      <webElementGuid>1d609e08-7114-44d5-a8e4-43f60432a254</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='__item104-__clone147-ModeCell']</value>
      <webElementGuid>e9b10b29-e024-4a35-a4ea-bf042f46e68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='__item104-__clone147']/td[2]</value>
      <webElementGuid>5c9b1bf5-8c06-496f-8758-072db8174ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overall Status'])[2]/following::td[2]</value>
      <webElementGuid>30e4314b-4f7e-4be5-9f20-9bdd161f54f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Updated On'])[2]/following::td[2]</value>
      <webElementGuid>3e7a66c3-d6f8-4113-a7d4-e2497832f2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EWM Goods Receipt'])[1]/preceding::td[2]</value>
      <webElementGuid>1b196da8-5f86-405b-884e-0fdd4569ca0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DDE - Plant'])[1]/preceding::td[3]</value>
      <webElementGuid>314ccbe5-bd6f-4f77-9ee5-621d4d367c32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>115e9787-86da-4da1-ac9a-e7a914579304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = '__item104-__clone147-ModeCell']</value>
      <webElementGuid>f2c8bf9c-9220-4369-82a0-5b69a2ac3811</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
