<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Overall Status_sapMListTblHighlightCell</name>
   <tag></tag>
   <elementGuidId>262fa93d-82ad-4817-b47f-5ecf231e07a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='__item104-__clone147']/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.sapMListTblHighlightCell</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.sapMListTblHighlightCell >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>075bd66e-bc60-4100-9753-286330bd2953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>b51049e3-0c1a-48dd-a649-f011bd173120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMListTblHighlightCell</value>
      <webElementGuid>467b9041-51ea-4973-9de2-1329ff2dd14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__item104-__clone147&quot;)/td[@class=&quot;sapMListTblHighlightCell&quot;]</value>
      <webElementGuid>f6505121-9ae9-43a5-bfba-f05cf07aee52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='__item104-__clone147']/td</value>
      <webElementGuid>4c5d396e-1d53-40bd-8930-dc9f05fda7ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>3d4dfaae-7435-49fb-84a1-c176e47f320e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
