<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Katalon Studio - TS02 - DM4MILL - GR</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>julie.hoste@delaware.pro;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>e2272ed7-7085-4603-b94a-79470dd241fc</testSuiteGuid>
   <testCaseLink>
      <guid>ef2400a5-8d51-40d3-893f-09dc95779ce7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>'julie.hoste@delaware.pro'</defaultValue>
         <description></description>
         <id>e9787488-641f-4226-90f2-dc7b5f32d649</id>
         <masked>false</masked>
         <name>username</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/DM4MILL - Goods Receipts</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9787488-641f-4226-90f2-dc7b5f32d649</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2c59cae-ee46-4a13-87b7-e2028f8556c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3da01a0e-42ed-46d9-a83f-d8b366bcc8d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7548b2d-3dcc-4369-a601-6a81ca82348d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
