# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: katalonpool
  demands:
  - agent.name -equals katalonagent


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: katalonTask@1
  inputs:
    version: '10.1.0'
    executeArgs: 'katalonc -noSplash -runMode=console -projectPath="C:\Users\hostej\OneDrive - delaware\Documents\GitHub\DM4MILL_Demo\DM4MILL.prj" -retry=0 -testSuitePath="Test Suites/Katalon Studio - TS02 - DM4MILL - GR - Demo" -browserType="Chrome" -executionProfile="Team" -apiKey="b9ce20fc-7bad-484d-908d-27ae7997e408"'
  displayName: 'AzureDevOps -  Katalon - DM4Mill_Demo'