<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>adc06c49-4673-4da2-8369-15c29b6efd02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#logOnFormSubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='logOnFormSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Continue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bf79f7d5-85b1-4901-b7fa-7ea15ffee347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ids-button fn-button ids-button--primary fn-button--emphasized ids-button--login js-button-login</value>
      <webElementGuid>dc869f53-70ed-48c9-9069-dd4618647178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form</name>
      <type>Main</type>
      <value>logOnForm</value>
      <webElementGuid>8760144f-6af1-4175-bdd9-a156c4923bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logOnFormSubmit</value>
      <webElementGuid>23a0d099-f7e0-435e-924c-84888b0f4711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d188ae35-53ed-450e-be94-9df7cc0bfff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c8738e77-7c32-41ca-96d2-d1363aae9307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>c513aa10-f11b-450b-bbfa-469c9b8db507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logOnFormSubmit&quot;)</value>
      <webElementGuid>e81f697e-c9e1-42f6-93c8-06ace3843375</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='logOnFormSubmit']</value>
      <webElementGuid>d91df798-49d9-481f-8acf-ad26f1bc2bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body']/main/div/div[3]/div/div[2]/div/div/button</value>
      <webElementGuid>8e6cdf8a-0455-4045-b286-614c9775bfca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email or User Name'])[1]/following::button[1]</value>
      <webElementGuid>f6adbc70-7d0a-4948-ac90-0329d7dbff80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[2]/following::button[1]</value>
      <webElementGuid>83436a4f-1c88-46e9-a148-b9a52c18a410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>10e8fde7-0752-48a8-8887-860e4da5d738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@form = 'logOnForm' and @id = 'logOnFormSubmit' and @type = 'submit' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>01872556-d820-4b6e-96cd-d791afd08b63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
