<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_I accept all cookies</name>
   <tag></tag>
   <elementGuidId>55b5a6d6-436e-4923-9712-5407330b96f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#truste-consent-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='truste-consent-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;I accept all cookies&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5f674691-27ce-4a2d-9d9e-88c1c131e890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>truste-consent-button</value>
      <webElementGuid>348abf6c-2345-4547-b0da-78ffd2cc97a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8f26e968-56cc-44f2-9e7d-9a1499bb6a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>truste-button1</value>
      <webElementGuid>75f27eea-f3d7-4f89-8649-915b4b86fed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I accept all cookies </value>
      <webElementGuid>d2486006-298a-4066-80eb-c108ae60d0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;truste-consent-button&quot;)</value>
      <webElementGuid>30f96008-4f5b-4efc-81ea-efc18f154f2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='truste-consent-button']</value>
      <webElementGuid>809ba0cb-6ce5-4aa3-b52b-b762e9c317e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='truste-consent-buttons']/button</value>
      <webElementGuid>dae87534-92b3-4af6-b43a-1d8ea56092fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookie Preferences'])[1]/following::button[1]</value>
      <webElementGuid>161c3cd7-61ba-4e84-ab07-00d30949ed10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject All'])[1]/preceding::button[1]</value>
      <webElementGuid>66bd87bc-fd88-485f-8df9-c353cd9e8b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View and change cookie preferences'])[1]/preceding::button[2]</value>
      <webElementGuid>0f265c27-9b4b-4368-89b0-0751297121a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='I accept all cookies']/parent::*</value>
      <webElementGuid>56a49167-fc77-43c2-8f6d-2a88c7f67eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>9743f100-3725-4066-8b8a-8db6edc15321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'truste-consent-button' and @type = 'button' and (text() = 'I accept all cookies ' or . = 'I accept all cookies ')]</value>
      <webElementGuid>0e3f4cb6-9e9d-41c0-b8f6-e2f526636703</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
