<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Universal IDOopsWe cant seem to find th_807619</name>
   <tag></tag>
   <elementGuidId>3c9b6e94-26dc-4e19-9219-3e69256c3ebe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>main.h-100 > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Universal IDOops!We can't seem to find the page you're looking for.Error: 400006&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9af0668b-7c4c-4a88-8a48-7d9fa638958e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Universal IDOops!We can't seem to find the page you're looking for.Error: 400006Message: Invalid parameter valuePlease click the button below to get support.Get Support</value>
      <webElementGuid>0e3c451f-60fe-4c2f-9a74-6e1289642d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100&quot;]/div[1]</value>
      <webElementGuid>5c81cb7e-075c-4e55-bdaa-06fd2164f9cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div</value>
      <webElementGuid>1fe866d6-77b9-486a-b5bd-59adac327c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div</value>
      <webElementGuid>43888b44-42dc-4396-81bd-86488caed0c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Universal IDOops!We can&quot; , &quot;'&quot; , &quot;t seem to find the page you&quot; , &quot;'&quot; , &quot;re looking for.Error: 400006Message: Invalid parameter valuePlease click the button below to get support.Get Support&quot;) or . = concat(&quot;Universal IDOops!We can&quot; , &quot;'&quot; , &quot;t seem to find the page you&quot; , &quot;'&quot; , &quot;re looking for.Error: 400006Message: Invalid parameter valuePlease click the button below to get support.Get Support&quot;))]</value>
      <webElementGuid>3c3f07af-565a-4965-afeb-9b86efcd3602</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
