<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Julie Hoste(S0026841138)Delaware Consul_9c9cc7</name>
   <tag></tag>
   <elementGuidId>c878d26e-8bbb-49d9-8a8a-323a344621de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#S0026841138 > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='S0026841138']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Julie Hoste\(S0026841138\)Delaware Consulting CV \(Belgium\)$/ >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>662ae0fb-c918-408e-8d33-9d9fe5e38fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Julie Hoste(S0026841138)Delaware Consulting CV (Belgium)</value>
      <webElementGuid>d724ea70-53c4-4e47-ba0e-a2a7d956becb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;S0026841138&quot;)/div[1]</value>
      <webElementGuid>195ba505-3e8f-43e6-ac08-3fb66dde5766</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='S0026841138']/div</value>
      <webElementGuid>5e6e49cf-853f-47e7-9d3f-a3387cd8c258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order'])[1]/following::div[5]</value>
      <webElementGuid>873ea8be-2667-490d-a157-55de9e322502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nickname'])[1]/following::div[6]</value>
      <webElementGuid>7af0548b-266b-46c3-a267-eee169e0c2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div</value>
      <webElementGuid>90f3e393-3d1a-47e0-b95a-f15c17fd4719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Julie Hoste(S0026841138)Delaware Consulting CV (Belgium)' or . = 'Julie Hoste(S0026841138)Delaware Consulting CV (Belgium)')]</value>
      <webElementGuid>ab49c945-b69e-49e2-a062-1113c4f73b82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
