<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Julie Hoste(S0026841138)Delaware Consulting CV (Belgium)</name>
   <tag></tag>
   <elementGuidId>b059626a-a9a2-45b1-9182-ac4dd2c0cf0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.uid-selector-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='S0026841138']/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Julie Hoste(S0026841138)Delaware Consulting CV (Belgium)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>57d1b307-ceba-40ed-a1d9-26ee56e5f811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uid-selector-name</value>
      <webElementGuid>725f0f48-0b18-456e-8948-133a6e4e6cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Julie Hoste(S0026841138)Delaware Consulting CV (Belgium)</value>
      <webElementGuid>9a7e2ba3-e845-4fb3-9f16-90865a3096b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;S0026841138&quot;)/div[1]/div[2]/div[@class=&quot;uid-selector-name&quot;]</value>
      <webElementGuid>d337c705-8740-4a11-a89d-56c4f19c7d6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='S0026841138']/div/div[2]/div</value>
      <webElementGuid>e7088a4e-1ecb-4b4f-b48c-2c2dc9774f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order'])[1]/following::div[8]</value>
      <webElementGuid>d80dba76-d824-48a6-b3c7-be1d4a94e5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nickname'])[1]/following::div[9]</value>
      <webElementGuid>8224f20f-48c6-4e08-b10d-2eb22ea17eb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div</value>
      <webElementGuid>0dbf152a-74b1-4733-af5d-dfc18c728bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Julie Hoste(S0026841138)Delaware Consulting CV (Belgium)' or . = 'Julie Hoste(S0026841138)Delaware Consulting CV (Belgium)')]</value>
      <webElementGuid>063e9509-802f-4d38-affc-1a35f30909d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
