<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select an accountIn order to access the_953dac</name>
   <tag></tag>
   <elementGuidId>c0b9849d-cd30-4a8a-927e-9d52371c061e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.centered</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Select an accountIn order to access the site, you must select an account.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3b417c37-3318-44ec-9b94-f752d28d9b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>centered</value>
      <webElementGuid>3970afec-eceb-4e80-9965-a1f1fd715771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select an accountIn order to access the site, you must select an account.</value>
      <webElementGuid>e2c5162b-4e22-4a8c-b028-f89f5e543843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100&quot;]/div[@class=&quot;uid-newbox-withFooter&quot;]/div[@class=&quot;uid-newbox-wrapper&quot;]/div[@class=&quot;uid-newbox uid-newbox--small&quot;]/div[@class=&quot;uid-newbox__content&quot;]/div[@class=&quot;no-tracking trackingContainer&quot;]/div[@class=&quot;uid-accountSelector--animationContainer uid-accountSelector&quot;]/div[@class=&quot;centered&quot;]</value>
      <webElementGuid>fd09336c-052c-47ee-86e3-ac58526765ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div/div[2]/div/div/div</value>
      <webElementGuid>066a0089-e8ee-428c-a0e9-3eb6d30e74cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok'])[1]/following::div[4]</value>
      <webElementGuid>5f9125c1-819c-4c32-abba-9f3d7b8d59a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Universal ID'])[1]/following::div[10]</value>
      <webElementGuid>74a12a3f-0ca4-45b1-b910-3e3ca1625b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by:'])[1]/preceding::div[1]</value>
      <webElementGuid>975c8d82-535a-47db-ba64-6e31f4ce1673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div</value>
      <webElementGuid>48865cfe-7b3d-4c12-8932-ed737dbe45be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select an accountIn order to access the site, you must select an account.' or . = 'Select an accountIn order to access the site, you must select an account.')]</value>
      <webElementGuid>7473f0c9-8bf1-4774-9cf6-f89accc4f119</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
