<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Select</name>
   <tag></tag>
   <elementGuidId>22ad4485-b26d-40fe-97ef-bfe907406b93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--selectButton-BDI-content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--selectButton-BDI-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Select&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>23ae5cf2-cdfa-4064-bdcf-8bc5458c090b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--selectButton-BDI-content</value>
      <webElementGuid>49e2574d-222c-4dc8-89ec-fb965023d4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>601533f3-55d7-4989-8008-2bd6575015b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>70aa6223-386f-4460-aad5-560b9b2303e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--selectButton-BDI-content&quot;)</value>
      <webElementGuid>2e011aad-b9e4-421c-84a5-213cf28cb4b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--selectButton-BDI-content']</value>
      <webElementGuid>9a36e749-5c10-44f8-af83-fa9cdf9c4b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--selectButton-content']/bdi</value>
      <webElementGuid>13596313-3c57-45d8-ae5a-730d8986964b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[1]/following::bdi[1]</value>
      <webElementGuid>d1a04ad9-5228-4afb-8768-844eb233d16c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None'])[4]/following::bdi[1]</value>
      <webElementGuid>a2ef9012-31e2-460c-9756-7a7085102206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[2]/preceding::bdi[1]</value>
      <webElementGuid>aa856c4f-9832-45f4-a520-5b1b7acc17c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::bdi[1]</value>
      <webElementGuid>a3dd89fc-00ce-4daa-950f-dfa266057864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>9d20f046-b4f1-4939-b05b-4579bd59a61f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/button/span/span/bdi</value>
      <webElementGuid>d911d48c-7785-4bf6-a7b6-a3d9b85cd6ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = '__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--selectButton-BDI-content' and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>565a91ec-a7c7-4007-b016-bfa5069e6bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Load more items.'])[1]/following::bdi[1]</value>
      <webElementGuid>a76f7fd9-0536-42eb-8d2f-b25bba38b09b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
