<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Post GR</name>
   <tag></tag>
   <elementGuidId>f3f85ce2-7edc-4b22-bafa-d829f1d51586</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--btnGrPosting-BDI-content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--btnGrPosting-BDI-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Post GR&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>7269cc95-e7a9-4cac-87d6-974303601bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--btnGrPosting-BDI-content</value>
      <webElementGuid>234bdfce-a881-4c50-a028-7348b50f8923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>1ccc8b05-6333-4128-b0d5-100146d6e225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Post GR</value>
      <webElementGuid>f6497841-371a-4cce-aec2-d96be63f6fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--btnGrPosting-BDI-content&quot;)</value>
      <webElementGuid>0df4601c-096e-4629-9a31-4644d41c3a9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--btnGrPosting-BDI-content']</value>
      <webElementGuid>edce86cf-73e1-43d1-b24f-b4bdd9b477e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--btnGrPosting-content']/bdi</value>
      <webElementGuid>c621ef3d-7486-46c3-a1b1-8413c595bd07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info Label'])[1]/following::bdi[1]</value>
      <webElementGuid>dfd30715-854d-42db-9ffd-65d4c0214dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M'])[1]/following::bdi[1]</value>
      <webElementGuid>8d03a47c-feed-432d-9577-d07f91336252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Quantity'])[1]/preceding::bdi[1]</value>
      <webElementGuid>edbdc59e-d59e-43af-8a6a-9762d1455dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Orders'])[1]/preceding::bdi[1]</value>
      <webElementGuid>400f039c-b5df-4cf3-b7de-5010d47849f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Post GR']/parent::*</value>
      <webElementGuid>866e4361-ce24-4cc5-a397-92507734c8ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/button/span/span[2]/bdi</value>
      <webElementGuid>8c64bae4-f7df-4226-9ad3-e4d9c6718e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--btnGrPosting-BDI-content' and (text() = 'Post GR' or . = 'Post GR')]</value>
      <webElementGuid>2a9bf1c7-6e32-435a-ba49-fe402d71bad7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
