<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Integration Message Dashboard</name>
   <tag></tag>
   <elementGuidId>02f870e3-aeeb-4971-8ed6-8f8c09c551df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__box5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__box5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;__box5&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e9a1df8d-f125-4679-940f-41aa958b2179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__box5</value>
      <webElementGuid>f7fc8137-2b79-4ea8-93c9-9c2955c6ace5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__box5</value>
      <webElementGuid>7cf22215-7620-42d9-9c5b-e9e6c9f9b6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMFlexBox sapMHBox sapMFlexBoxJustifyStart sapMFlexBoxAlignItemsCenter sapMFlexBoxWrapNoWrap sapMFlexBoxAlignContentStretch sapMFlexBoxBGTransparent</value>
      <webElementGuid>1ead194e-083d-4adc-b268-ae965874f19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Integration Message Dashboard</value>
      <webElementGuid>e5255da7-6d32-4126-ab54-588abd9130f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__box5&quot;)</value>
      <webElementGuid>75211d50-c090-44e3-95c1-df50ba3df3e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='__box5']</value>
      <webElementGuid>96f46765-473c-498a-8ce3-324cbc7d8355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__item83-content']/div</value>
      <webElementGuid>3f76395d-53e1-412c-b905-71b3a66ed398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div</value>
      <webElementGuid>2db4fbf4-3723-481b-8d02-7e6120722fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '__box5' and (text() = 'Integration Message Dashboard' or . = 'Integration Message Dashboard')]</value>
      <webElementGuid>f2c715f8-3d87-4a09-b7a9-6669f76c5e71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
