<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Integration Message Dashboard_1</name>
   <tag></tag>
   <elementGuidId>aa845302-6af3-4e11-bfb6-e1011b206cab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__box19</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__box19']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;__box19&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e940daab-72c8-46ad-b08e-b5078a66bf21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__box19</value>
      <webElementGuid>b039ff8d-293d-4c43-a337-3a18b545fded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__box19</value>
      <webElementGuid>c952f28f-fca2-4e7c-a3c1-24388416cfbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMFlexBox sapMHBox sapMFlexBoxJustifyStart sapMFlexBoxAlignItemsCenter sapMFlexBoxWrapNoWrap sapMFlexBoxAlignContentStretch sapMFlexBoxBGTransparent</value>
      <webElementGuid>1a0841ca-acd7-4139-8241-4727ccde584e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Integration Message Dashboard</value>
      <webElementGuid>4238d3ea-91e2-47bc-80e5-ec83320d31c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__box19&quot;)</value>
      <webElementGuid>170854d1-559f-4dfe-ad00-b7dd9235ee3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='__box19']</value>
      <webElementGuid>5686bacd-6d5e-4365-80b5-9bb105c53f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__item190-content']/div</value>
      <webElementGuid>3a07309d-be96-415a-bab7-7a8444b37e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div</value>
      <webElementGuid>f6715e11-83b3-4828-aca4-eb1c2bfc397e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '__box19' and (text() = 'Integration Message Dashboard' or . = 'Integration Message Dashboard')]</value>
      <webElementGuid>702e8326-5fc4-4fd6-a5b5-43fdd7b2ed7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
