<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_GR Qty MInfo LabelPost GRSubmit Quantity</name>
   <tag></tag>
   <elementGuidId>f9862a50-f5c5-460b-a95b-393d87ca1897</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__box2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__box2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;GR Qty :MInfo LabelPost GRSubmit Quantity&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a0bada10-d840-48dc-a3e3-6039871cb527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__box2</value>
      <webElementGuid>828d2035-7078-4563-9b78-8d1cd9320725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__box2</value>
      <webElementGuid>599783d4-3ead-4ee3-8527-5729653e6956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMFlexBox sapMHBox sapMFlexBoxJustifyEnd sapMFlexBoxAlignItemsCenter sapMFlexBoxWrapNoWrap sapMFlexBoxAlignContentStretch sapMFlexBoxBGTransparent sapMFlexItem</value>
      <webElementGuid>ad77e7d8-614d-4dd4-a214-d372f4107eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GR Qty :MInfo LabelPost GRSubmit Quantity</value>
      <webElementGuid>2299a44c-fe40-4b1d-a6f6-fac3b5591e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__box2&quot;)</value>
      <webElementGuid>595f8f75-e52f-45e1-b50f-6f87e1e95f14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='__box2']</value>
      <webElementGuid>5d4f5ad8-e130-4c96-86fa-1d8fdbca1df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--fGRPosts']/div[3]</value>
      <webElementGuid>7f8b9804-8123-4c0b-afe2-a9cdf257058d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[3]/following::div[13]</value>
      <webElementGuid>01ad56cc-9e26-4b60-b4a4-7c6e49a1c2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scrap Postings'])[1]/following::div[19]</value>
      <webElementGuid>7d4c2e59-3265-4086-9868-3c8bfaeeeed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div[3]</value>
      <webElementGuid>985b594c-db93-47b2-9fd6-2390c0ec15c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '__box2' and (text() = 'GR Qty :MInfo LabelPost GRSubmit Quantity' or . = 'GR Qty :MInfo LabelPost GRSubmit Quantity')]</value>
      <webElementGuid>9c26e476-4150-4112-a572-9fcb8113c5a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
