<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Clear___xmlview100--reservedComponentCo_b6c65f</name>
   <tag></tag>
   <elementGuidId>0970ed9f-9690-4d01-bd66-3f31001fead9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--resultTable-sa-CbBg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--resultTable-sa-CbBg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Select Work Center&quot;i >> internal:label=&quot;Select all rows&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a861b379-ec01-4c28-ad47-5b339f1598cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--resultTable-sa-CbBg</value>
      <webElementGuid>3d3022f5-d23a-4de5-a2ae-cbc8a1e5ba4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMCbBg sapMCbHoverable sapMCbActiveStateOff sapMCbMark</value>
      <webElementGuid>67f65f92-c73e-400a-87dc-3054c8f77b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--resultTable-sa-CbBg&quot;)</value>
      <webElementGuid>d134de3a-f9cb-4095-a7ed-52c231e74521</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--resultTable-sa-CbBg']</value>
      <webElementGuid>18664c3d-f6c1-4e22-96d0-1726e9f28d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--resultTable-sa']/div</value>
      <webElementGuid>aced728b-c774-48aa-83a6-b05e716693ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/following::div[4]</value>
      <webElementGuid>b5802523-291f-435c-91e2-7880841e2325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Filter Bar'])[1]/following::div[4]</value>
      <webElementGuid>c832a4b2-4ef8-423c-b89a-4b05c787b26c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[1]/preceding::div[1]</value>
      <webElementGuid>afb0f15e-8bae-444c-ab66-500cba81eb82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Center'])[1]/preceding::div[1]</value>
      <webElementGuid>ba67824b-9df0-4c45-a5d7-08bfc297ae52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/div/div</value>
      <webElementGuid>2d279fe2-3132-47d1-8f1d-2982d5633f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--resultTable-sa-CbBg']</value>
      <webElementGuid>ea855800-b88a-4b68-bccc-61e84baf0616</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
