<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Clear___xmlview100--reservedComponentCo_b6c65f</name>
   <tag></tag>
   <elementGuidId>0970ed9f-9690-4d01-bd66-3f31001fead9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--resultTable-sa-CbBg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--resultTable-sa-CbBg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Select Work Center&quot;i >> internal:label=&quot;Select all rows&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1b0a8305-178a-4763-bae6-f3d6759ad8a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--resultTable-sa-CbBg</value>
      <webElementGuid>6e4c0a03-370a-42e7-840b-fcb0e328bb60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMCbBg sapMCbHoverable sapMCbActiveStateOff sapMCbMark</value>
      <webElementGuid>56713f95-96ec-4be1-84f1-dd6a3f2859ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--resultTable-sa-CbBg&quot;)</value>
      <webElementGuid>18f461ab-847d-4f9d-a633-ecad429bdd9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--resultTable-sa-CbBg']</value>
      <webElementGuid>9c6d27f9-ad7b-4651-9a20-10a314b868b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--resultTable-sa']/div</value>
      <webElementGuid>d9036f0e-a189-408f-859f-1f68499d326a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/following::div[4]</value>
      <webElementGuid>dcb75e35-5c7a-427a-a7d5-b2c785961c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Filter Bar'])[1]/following::div[4]</value>
      <webElementGuid>4776b482-99de-44b3-8145-bf628d41f7cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[1]/preceding::div[1]</value>
      <webElementGuid>e63c8b89-0569-4337-8dcc-3b45eca101ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Center'])[1]/preceding::div[1]</value>
      <webElementGuid>8a616595-e1d4-4b1d-975c-5bf17d715c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/div/div</value>
      <webElementGuid>10f0cb39-4ee0-4b16-b775-89f1a083a94f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--resultTable-sa-CbBg']</value>
      <webElementGuid>b3c7e122-fc73-49c4-8c29-9182f6b01915</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
