<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Quantity Confirmed Successfully</name>
   <tag></tag>
   <elementGuidId>8b9c1e1c-c420-4fce-9389-fc9ee8f97e0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sap-ui-static']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sapMMessageToast.sapUiSelectable.sapContrast.sapContrastPlus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Quantity Confirmed Successfully&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5f28691e-2e65-40b2-aef8-602767b6a985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMMessageToast sapUiSelectable sapContrast sapContrastPlus</value>
      <webElementGuid>cf84e272-0889-48c5-88d8-14c7bd2cfc27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>7b6ae7f8-e11a-4ca1-a2b5-b291e9067a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-popup</name>
      <type>Main</type>
      <value>id-1741960545763-645</value>
      <webElementGuid>29add788-e048-4d3c-9208-7dbe06c89b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quantity Confirmed Successfully</value>
      <webElementGuid>4d846f6c-0e58-4980-9636-2eee1da388bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sap-ui-static&quot;)/div[@class=&quot;sapMMessageToast sapUiSelectable sapContrast sapContrastPlus&quot;]</value>
      <webElementGuid>05f7749f-fcfb-4586-a653-fcadd7121f26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sap-ui-static']/div[2]</value>
      <webElementGuid>6094f39f-e337-416b-a3c8-29866ad990d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[6]</value>
      <webElementGuid>3e692665-3571-44ce-8b19-2ea3f9056b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DDE_DM4MILL_GR_FINAL'])[2]/preceding::div[6]</value>
      <webElementGuid>cd1a29c5-12f8-429a-8444-091129dff38f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Quantity Confirmed Successfully']/parent::*</value>
      <webElementGuid>ddaf0fca-4289-4848-a17a-fdc5dd2ac894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>be097b97-0c48-40c3-a89b-5370b21eaecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Quantity Confirmed Successfully' or . = 'Quantity Confirmed Successfully')]</value>
      <webElementGuid>bd7b8b36-3314-445d-b916-6c86b3d78829</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
