<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_GR Qty_DETAILSView--icontabfilterCSGX_c763b3</name>
   <tag></tag>
   <elementGuidId>6a64e78b-48db-4c1d-8aca-6a8356cf48f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--inputQTY-inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--inputQTY-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;GR Qty&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83efbe1d-14c0-45b5-b620-0ed25e6b1019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--inputQTY-inner</value>
      <webElementGuid>f00ad333-8bfa-4ef8-99b9-776dee868ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>GR Qty</value>
      <webElementGuid>70152035-0880-4044-9af7-7048b7a0e06f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>f9729324-97df-49dc-9cd0-322254c42f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d5428344-c858-4199-9a1c-d33244fd7afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>df0c4157-d539-485f-9d4b-5253bcada6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>b3e86244-7f88-41b5-a756-8c6c46eb4068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--inputQTY-inner&quot;)</value>
      <webElementGuid>b7b94ae4-2c98-48de-a401-167805e5da58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--inputQTY-inner']</value>
      <webElementGuid>bdd6f5aa-8559-4ca4-8731-a172d4584d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--inputQTY-content']/input</value>
      <webElementGuid>28129c85-dae5-4c13-8867-243bab4f55eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div/div/input</value>
      <webElementGuid>7a8629fe-c68e-4c8e-953b-feba56f0f195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--inputQTY-inner' and @placeholder = 'GR Qty' and @type = 'text']</value>
      <webElementGuid>97f59bf8-4881-475d-a329-abd2cef26d18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
