<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_GR Qty_DETAILSView--icontabfilterCSGX_c763b3</name>
   <tag></tag>
   <elementGuidId>6a64e78b-48db-4c1d-8aca-6a8356cf48f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--inputQTY-inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--inputQTY-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;GR Qty&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9def0e2-dfce-4914-b73e-da89ad5b62cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--inputQTY-inner</value>
      <webElementGuid>b86a7c3d-71e1-497d-b5a9-72b1033c83cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>GR Qty</value>
      <webElementGuid>a958fd1a-d14d-48a4-996f-ae43c42050cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>a63836a5-afea-4740-ba5f-22fa8a9a731e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9ab0a1b6-fa2e-4729-b144-ca6a51afdea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0ae604bc-58b2-4b69-bce2-4d774a061857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>10220f6c-b52e-4844-ad7d-25899c011c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--inputQTY-inner&quot;)</value>
      <webElementGuid>dd876619-3c9b-4436-b096-f5c10aabad72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--inputQTY-inner']</value>
      <webElementGuid>4ed688e7-f70d-4d49-96ab-709ecceb39ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--inputQTY-content']/input</value>
      <webElementGuid>3676e278-c48a-4d78-9fe6-a65e04847ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div/div/input</value>
      <webElementGuid>7399178d-7995-402b-a229-a69e9229cb6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--inputQTY-inner' and @placeholder = 'GR Qty' and @type = 'text']</value>
      <webElementGuid>f1984918-e37b-4f39-88a9-b014ea0ea3ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
