<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_GR Qty_DETAILSView--icontabfilterCSGX_c763b3</name>
   <tag></tag>
   <elementGuidId>6a64e78b-48db-4c1d-8aca-6a8356cf48f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--inputQTY-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--inputQTY-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;GR Qty&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4357e69e-2d86-49bb-9751-1a3652051545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--inputQTY-inner</value>
      <webElementGuid>0186a059-d6b6-4d7f-ab59-3f42ae73e01e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>GR Qty</value>
      <webElementGuid>c138e4f7-e10f-4591-8f3f-199babfefaf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>7565f8af-5f92-4d7b-850b-30965b40b0fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a159870c-372d-4a7d-8f4e-3e873507eabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>21c5b601-18cc-426a-8638-8895fc5641b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>69c0d87c-1d8e-4b04-a19c-9184f256b856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--inputQTY-inner&quot;)</value>
      <webElementGuid>a1b21ad5-9fd5-40f2-9eea-9a865191ae5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--inputQTY-inner']</value>
      <webElementGuid>342b4d26-946b-4710-93bc-fb43a2e545a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--inputQTY-content']/input</value>
      <webElementGuid>7eb6436b-4613-4472-93e3-0941c6e5bf94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div/div/input</value>
      <webElementGuid>62e6f8c8-1a3d-494a-8fcb-7b9b1f1d483e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--inputQTY-inner' and @placeholder = 'GR Qty' and @type = 'text']</value>
      <webElementGuid>eed3cb92-46fc-4316-a2e4-d581cc4a6b4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
