<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Plant 1210 ( DDE - Plant )_search</name>
   <tag></tag>
   <elementGuidId>51b2951e-ac2f-4957-89bf-aa52eae08891</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchFieldInShell-input-inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchFieldInShell-input-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search In: \&quot;Apps\&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af34ba1c-4de1-4418-9b7b-1ce4a69cb385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchFieldInShell-input-inner</value>
      <webElementGuid>5913a017-b005-4884-95a8-890cba3a7c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search In: &quot;Apps&quot;</value>
      <webElementGuid>d3c5fd08-a4fd-41d5-800b-344d27052e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>searchFieldInShell-input-No-Results-Description</value>
      <webElementGuid>605ae2c5-ac8b-44df-aad0-81703b2b6184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>f18e7143-c618-4dd3-aa16-ba5ce0bf316e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>0bfa8333-fe19-4e44-8762-264b652a3e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>724283ed-c7ba-4853-8970-e4d69318f392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>25292c98-c86d-474d-a14c-0ab9a5267370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1b8aee41-aaa6-4eea-bd1c-ecb76c70017c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>2e39d00a-de00-4cdb-9255-63eda87d690f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchFieldInShell-input-inner&quot;)</value>
      <webElementGuid>4eaf3610-e128-48d7-b8e3-078c092eab5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchFieldInShell-input-inner']</value>
      <webElementGuid>a6805b15-7e6f-40ae-acbc-1ceff45d8f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchFieldInShell-input-content']/input</value>
      <webElementGuid>57c6ba74-3da1-457f-86b6-f1a6268e9f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>aa2eaf77-8e89-4ce9-afce-16fa5869e234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'searchFieldInShell-input-inner' and @placeholder = 'Search In: &quot;Apps&quot;' and @type = 'search' and @name = 'search']</value>
      <webElementGuid>6c7c9aa9-7999-47e9-8054-67ac45578da2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
