<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select Work Center___xmlview100--rese_915078</name>
   <tag></tag>
   <elementGuidId>a3696fc4-9163-47d0-a117-799af27ca9a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--searchField-I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--searchField-I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Select Work Center&quot;i >> internal:attr=[placeholder=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5bbccb59-2d3c-44ad-8f95-dd9018d3fabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--searchField-I</value>
      <webElementGuid>188c4b4d-202f-4847-954f-faa5aa3fe05d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>bd92740b-664e-4a0c-ba55-7bbf4dcc79ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>03b0c0e4-07d8-44a3-a97f-00adac17760e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>794d73f3-4705-405f-9857-5ae12ea7f38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>f11c3755-fcdb-4a7e-a6e4-bb1fde14d1e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>6cc23141-06a7-4676-8035-64c5bf49c412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text50</value>
      <webElementGuid>8907fe8a-a7a8-4283-90a4-1ea470a87386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMSFI</value>
      <webElementGuid>2d0e38db-9c5a-4357-a705-8540866bd4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--searchField-I&quot;)</value>
      <webElementGuid>32e695c1-9f23-4361-a575-fae886faf369</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--searchField-I']</value>
      <webElementGuid>02c2a4c5-3e6f-47d8-bd10-c9ccfbeb9fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--searchField-F']/input</value>
      <webElementGuid>d99aa184-baad-477a-a17a-a02506564936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>43adad8d-d072-44bb-bc4c-76b93c658983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--searchField-I' and @type = 'search' and @placeholder = 'Search']</value>
      <webElementGuid>69bbdd6b-c8e7-4689-8c33-28d3105617a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
