<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Order ID___xmlview100--reservedCompon_66eb78</name>
   <tag></tag>
   <elementGuidId>60946caa-7f04-4b31-9059-8249fea436ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--orderIdFilter-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--orderIdFilter-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Order ID&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2ecd775-4192-42e8-91b3-b3a40b5fb61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--orderIdFilter-inner</value>
      <webElementGuid>4233b8fb-4309-499c-9374-72c141337fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--filterBar-filterItem-___INTERNAL_-ORDERID</value>
      <webElementGuid>0fd8c66c-9f29-4d91-8760-f24cb49f6393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text32</value>
      <webElementGuid>f7f5ce7a-978a-4e3f-87a6-9f23437e2458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>51e29912-7e6d-4867-89db-ab8717d74110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-roledescription</name>
      <type>Main</type>
      <value>Multi Value Input</value>
      <webElementGuid>8045dff1-82b7-4937-b338-56d4aba97276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>718f9064-1fa2-4b7a-94bc-8546be6e478f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2bc535e7-a74e-4661-9da1-ecc7f9881b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>fae719dd-0eda-4d9d-9f13-b658837cad59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--orderIdFilter-inner&quot;)</value>
      <webElementGuid>08875851-6112-422d-b63d-807a5ee59663</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--orderIdFilter-inner']</value>
      <webElementGuid>74d036e4-99a6-43fb-b990-09663f2c17ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--orderIdFilter-content']/input</value>
      <webElementGuid>78c70dfc-6f27-4842-9332-7323cf1c969b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>7559f3fa-d786-4ebb-a780-14e738b8de0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--orderIdFilter-inner' and @type = 'text']</value>
      <webElementGuid>ba9fa5e3-cdcd-4698-b024-d8160928c1bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
