<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select Work Center___xmlview100--rese_915078</name>
   <tag></tag>
   <elementGuidId>a3696fc4-9163-47d0-a117-799af27ca9a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--searchField-I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--searchField-I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Select Work Center&quot;i >> internal:attr=[placeholder=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84818c5b-1491-4724-b3e0-3c72f03320ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--searchField-I</value>
      <webElementGuid>80c04cb0-6db5-43a8-b832-1cedd7c3f111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>c3171bf0-a83e-44e6-b966-1c8b51e3d155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>6bdbc567-ec14-4844-b4f6-dc2f71876cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b4f605e5-bb24-4db2-9503-19aee72e26a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>2832f326-fcfa-4c7f-8cdc-ac4e6f078c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>984b6e8e-c6c3-421f-a0bf-c0ce8b443ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text50</value>
      <webElementGuid>92d666fd-168e-4eb9-884a-e52913ad2db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMSFI</value>
      <webElementGuid>74d30386-07f0-4966-9380-42fcadfbfd0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--searchField-I&quot;)</value>
      <webElementGuid>aaa15ae9-8bd2-40a2-b47c-9e893d648e32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--searchField-I']</value>
      <webElementGuid>1d7e3704-4e6b-402e-a1ec-f9ed6733747e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--searchField-F']/input</value>
      <webElementGuid>faf29b9d-d6aa-4cbb-8799-8dfecf5511c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ac2d724a-886e-482c-8cfa-93e8c46605ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterBrowse--searchField-I' and @type = 'search' and @placeholder = 'Search']</value>
      <webElementGuid>04d96807-f0ff-4366-89cf-065ade6d883e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
