<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Integration Message Dashboard</name>
   <tag></tag>
   <elementGuidId>381b1456-19c8-4b1b-923d-49de85600c6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__text139</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__text139']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Integration Message Dashboard&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>85d670bf-fc8a-4a18-a4d3-61f026b03f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__text139</value>
      <webElementGuid>3c72bc3f-5a2e-4b23-8db7-ff011d27c4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__text139</value>
      <webElementGuid>49ecd215-0a28-45aa-bd7c-ee96f94ff037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>705ed42a-c9cb-4142-b571-f6cdc0824b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapUiSelectable sapMTextNoWrap sapMTextMaxWidth suggestText suggestNavItem suggestListItemCell</value>
      <webElementGuid>fe14e7b9-11e8-4851-a135-15621ac18852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Integration Message Dashboard</value>
      <webElementGuid>67279dab-13a9-40ad-99e8-c88997edaae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__text139&quot;)</value>
      <webElementGuid>7ec06744-6ef2-4fb6-9f76-b894a9fda406</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__text139']</value>
      <webElementGuid>ef73bd3e-5b08-48fe-a6b7-95a0b4c7d4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__data317']/span</value>
      <webElementGuid>8b350205-ec9a-4aa1-8473-ec56e6c1d998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='gration Message Dashboard']/parent::*</value>
      <webElementGuid>b1475b2e-7bad-432c-a9a3-98d1e09560f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/span</value>
      <webElementGuid>9be4d973-f974-45ad-bfe4-928b09851457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__text139' and (text() = 'Integration Message Dashboard' or . = 'Integration Message Dashboard')]</value>
      <webElementGuid>b0db673f-4f76-4ee7-bdc6-7b403e35f5d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__text134']</value>
      <webElementGuid>c10c77d7-28ec-4a68-8d1d-f6cff710ccaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__data307']/span</value>
      <webElementGuid>02cf7854-884e-40d2-868f-e036c4ad5278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ation Message Dashboard']/parent::*</value>
      <webElementGuid>f5ae9881-4122-4b4a-9c2a-35d10043cac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__text134' and (text() = 'Integration Message Dashboard' or . = 'Integration Message Dashboard')]</value>
      <webElementGuid>c2a5a502-aa5b-4490-8fc1-33097389bc67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
