<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Work Center___xmlview100--reservedComp_9efbcc</name>
   <tag></tag>
   <elementGuidId>f5b8b4b8-fcd2-4f25-9b53-fbb67e3d82d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterFilter-vhi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterFilter-vhi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterFilter-vhi&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>66972a91-a67f-4159-96cf-634b1361fe9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterFilter-vhi</value>
      <webElementGuid>7c962df0-4fc1-4c59-ae41-90d25c52164e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterFilter-vhi</value>
      <webElementGuid>b9aca371-495d-4b94-8b33-2e59605ff89c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e8867dd5-14fa-4d44-8533-8c06fa05a29d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Show Value Help</value>
      <webElementGuid>0a5c4b22-77e3-45bd-9eae-ad2c156ca18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>5040c3fb-8890-4057-9628-f1a363ec0b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIcon sapUiIconMirrorInRTL sapUiIconPointer sapMInputBaseIcon</value>
      <webElementGuid>d465d83a-ce31-4c3c-8373-f5c1804d08f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterFilter-vhi&quot;)</value>
      <webElementGuid>a4bdb86b-99e4-4a34-beda-e84200e21897</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterFilter-vhi']</value>
      <webElementGuid>f4de4319-6742-40f8-b9ed-3e0a837b0627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterFilter-content']/div[2]/span[2]</value>
      <webElementGuid>90cb7be2-7750-4afd-b584-53d6f12faf4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[2]</value>
      <webElementGuid>f58a50c9-ec6a-47cb-893a-7a888d876cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterFilter-vhi']</value>
      <webElementGuid>d5ab8ba3-07fb-474f-9fd7-c6a0d60f181b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
