<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Mill Goods Receipt</name>
   <tag></tag>
   <elementGuidId>b6174c04-388d-4e1c-9b6a-722531127410</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DETAILSView--icontabfilterCSGXHZB1-text > span.sapMITHTextContent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='DETAILSView--icontabfilterCSGXHZB1-text']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Mill Goods Receipt&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1a6e7175-db95-4d10-ba33-36f2b301ea44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>298af6a0-162a-4439-a9ba-dc15be264d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMITHTextContent</value>
      <webElementGuid>5057d564-2422-4e9f-86e2-1abd20bd4574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mill Goods Receipt</value>
      <webElementGuid>e6772318-6bc4-4f13-8f72-2134afba39ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DETAILSView--icontabfilterCSGXHZB1-text&quot;)/span[@class=&quot;sapMITHTextContent&quot;]</value>
      <webElementGuid>cff850ad-c5c0-4a2a-a71b-b6fa982c49c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DETAILSView--icontabfilterCSGXHZB1-text']/span</value>
      <webElementGuid>0e9af46e-147a-4f91-a82f-c72ec69ebdf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operation Details'])[1]/following::span[2]</value>
      <webElementGuid>339a4a0d-8759-4fe3-8d36-8eb9a808c4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Positive'])[1]/following::span[5]</value>
      <webElementGuid>83f8eeca-6e1a-4a73-aacd-8ae9eda1bdae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[2]/preceding::span[3]</value>
      <webElementGuid>1634eef1-f91c-4fb1-887d-caf92f5038eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operation ID'])[2]/preceding::span[11]</value>
      <webElementGuid>6f5aa0b0-3434-4380-a116-a1b0dc2478f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mill Goods Receipt']/parent::*</value>
      <webElementGuid>23a207f6-b026-4e64-8717-1ff88fcfe6ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/span</value>
      <webElementGuid>bbd3a2fd-9e9b-477a-90cc-7d0917f1826b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Mill Goods Receipt' or . = 'Mill Goods Receipt')]</value>
      <webElementGuid>639a328d-77ee-40c0-aec2-2f8682dfdf3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
