<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_4 M</name>
   <tag></tag>
   <elementGuidId>75b4827c-8aee-4919-8fb9-5bda355c9aab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__text116-__clone138</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__text116-__clone138']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;4 M&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>742e92cc-161b-4ec6-8b18-9318d8f0b560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__text116-__clone138</value>
      <webElementGuid>ce8439ee-a367-49ea-802e-5b3c62c05bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__text116-__clone138</value>
      <webElementGuid>1e0545cc-2b6e-4782-856d-05fe6f9b15d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>686e9fb2-2412-4f2f-82cf-0468c7680069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapUiSelectable sapMTextMaxWidth</value>
      <webElementGuid>fb88eb24-a007-42c5-889b-adbb557ea5cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4 M</value>
      <webElementGuid>aa84863e-13e8-4858-94d8-2057e1c0a977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__text116-__clone138&quot;)</value>
      <webElementGuid>c9b8eb5e-11c3-4368-bb9b-ed25cfc5ab28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__text116-__clone138']</value>
      <webElementGuid>0595ff34-091f-429f-9c39-d38fb079f4c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='__item80-__clone138-cell4']/span</value>
      <webElementGuid>ba109c85-4574-4492-b391-1aa154e43736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DDE-101-0500-2500'])[3]/following::span[1]</value>
      <webElementGuid>5c80cf25-4e3b-411c-bb40-94fe4b21a21e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mar 04, 2025, 4:51:02 PM'])[1]/following::span[4]</value>
      <webElementGuid>07631461-d164-44cf-a7e5-c01f284ee2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mar 04, 2025, 4:36:17 PM'])[1]/preceding::span[5]</value>
      <webElementGuid>c183159b-9347-4221-9bed-428173682dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DDE-101-0500-2500'])[4]/preceding::span[8]</value>
      <webElementGuid>4fe94aaa-b299-47d9-9463-614439fa9098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='4 M']/parent::*</value>
      <webElementGuid>38925599-9a70-4da1-954d-14715796c13b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr/td[6]/span</value>
      <webElementGuid>8e5f2c39-3fe8-4459-b686-c8be26892ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__text116-__clone138' and (text() = '4 M' or . = '4 M')]</value>
      <webElementGuid>b9aae949-6a8c-4789-8887-9e11a915b0dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
