<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Info Label_DETAILSView--icontabfilterC_26f3c2</name>
   <tag></tag>
   <elementGuidId>e1f68aaa-9ff3-4ce5-b72e-f1cef0b35fb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--btnGrPosting-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--btnGrPosting-img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Post GR&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7f034b40-38e6-494d-a2a7-73a52952f5b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--btnGrPosting-img</value>
      <webElementGuid>4333895d-4408-4244-b780-b63dbd8c659e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--btnGrPosting-img</value>
      <webElementGuid>b5470226-6032-4b3e-b1d5-a139591ffbba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>8141dc42-ee06-4bec-82ad-a9324e554984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>14cdd6a5-6a1d-4d3f-9966-d39c1573f600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>1b1b5878-3f9a-408b-aa15-7bfbf4104f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIcon sapUiIconMirrorInRTL sapMBtnCustomIcon sapMBtnIcon sapMBtnIconLeft</value>
      <webElementGuid>e1e0ace8-7763-470d-b392-57ffd0658475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--btnGrPosting-img&quot;)</value>
      <webElementGuid>c9c6ea2d-8e58-4392-bfae-3818cf9bfcb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--btnGrPosting-img']</value>
      <webElementGuid>eed51ac3-c914-455f-be6e-b5d63ff3e9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--btnGrPosting-inner']/span</value>
      <webElementGuid>6c694a56-deb6-4aa6-b9a5-515dbed27615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/button/span/span</value>
      <webElementGuid>edfd05b2-f7fa-4b95-a4c9-9787c4b6ec86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'DETAILSView--icontabfilterCSGXHZB1_plugin---MainView--btnGrPosting-img']</value>
      <webElementGuid>a9f07f21-c288-4d39-b30f-0fe9d7dd8109</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
