<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Go</name>
   <tag></tag>
   <elementGuidId>b9eb0864-bada-4f47-954f-27eb82f8bc7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--filterBar-btnGo-inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--filterBar-btnGo-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Go&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e2877ced-7d0b-4fdf-ae0b-1f615e4bf7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--filterBar-btnGo-inner</value>
      <webElementGuid>33d949cb-8462-4eea-b5a3-6f85bc1398db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMBtnInner sapMBtnHoverable sapMFocusable sapMBtnText sapMBtnEmphasized</value>
      <webElementGuid>d57cd017-580a-4f25-ae84-4b932e95169f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>4a5a2b14-f999-441a-b140-0c193731a7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--filterBar-btnGo-inner&quot;)</value>
      <webElementGuid>d28bc616-a2ff-4180-81dc-50d8824d61f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--filterBar-btnGo-inner']</value>
      <webElementGuid>300f9b3f-3e77-4adc-92f1-4c50ab7c4efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--filterBar-btnGo']/span</value>
      <webElementGuid>3a028b1e-cbb3-42dc-ac7c-519f4c3a12d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Planned Start Date Range'])[1]/following::span[3]</value>
      <webElementGuid>d142f371-f9f3-4dab-a07b-3db481bbd8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SFC Status'])[1]/following::span[9]</value>
      <webElementGuid>cd68b6a8-88c2-4f40-a0ac-6b0b119e9c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/preceding::span[2]</value>
      <webElementGuid>a5ec57e1-bfab-45f8-8e21-4bd8b11df995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/button/span</value>
      <webElementGuid>9e851a07-81ab-4d91-b898-ad42e83ed3ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--filterBar-btnGo-inner' and (text() = 'Go' or . = 'Go')]</value>
      <webElementGuid>49168238-998d-4803-b751-2c9791524dff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
