<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Work Center___xmlview100--reservedComp_9efbcc</name>
   <tag></tag>
   <elementGuidId>f5b8b4b8-fcd2-4f25-9b53-fbb67e3d82d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterFilter-vhi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterFilter-vhi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterFilter-vhi&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dcb69115-a8d3-46fe-9235-6dfd5e1b9dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterFilter-vhi</value>
      <webElementGuid>b308905d-17a4-43da-8d4c-1528151dbcf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterFilter-vhi</value>
      <webElementGuid>9af629a5-c4f1-4ec1-a49b-306d9fc2ec08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6d11238c-bd6c-4694-9f4c-ea0c993dc44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Show Value Help</value>
      <webElementGuid>a586f88c-0b6d-47b2-9c66-e7335dc3332d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>2bfecde7-b077-4c30-b1ec-796d4d079b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIcon sapUiIconMirrorInRTL sapUiIconPointer sapMInputBaseIcon</value>
      <webElementGuid>1ef1e745-4d8e-4aba-8d51-2c6f0a20d934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterFilter-vhi&quot;)</value>
      <webElementGuid>310c5589-ba0f-4d5f-8e03-89a875fa4f2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterFilter-vhi']</value>
      <webElementGuid>14cb93a8-494b-4ed3-bf85-b43f86b58489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterFilter-content']/div[2]/span[2]</value>
      <webElementGuid>ed837fbb-893d-4fff-bfe6-0ea30eca390a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[2]</value>
      <webElementGuid>5021e81b-112c-465d-9152-c0a333511abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--workCenterFilter-vhi']</value>
      <webElementGuid>d482d8e6-73ba-468c-884d-ac7426426a31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
