<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Plant 1210 ( DDE - Plant )_searchField_91847b</name>
   <tag></tag>
   <elementGuidId>0ea59451-5b86-4069-b30d-a9cba0b2bf3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchFieldInShell-button-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Focus Search&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cf269341-5509-4b14-92c6-39bdf21c8dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchFieldInShell-button-inner</value>
      <webElementGuid>28d87a49-c3a4-45af-915a-087f2ed8ea3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMBtnInner sapMBtnHoverable sapMFocusable sapMBtnIconFirst sapMBtnDefault</value>
      <webElementGuid>e84cc91a-2179-422c-8e55-a0bd2f49a20a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchFieldInShell-button-inner&quot;)</value>
      <webElementGuid>7d6d6863-c3d3-4c10-97f3-ec87f1c85000</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='searchFieldInShell-button-inner']</value>
      <webElementGuid>736fc5d1-2e30-43c6-aace-28c821ee6ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='searchFieldInShell-button']/span</value>
      <webElementGuid>2e657773-3c6f-4625-a455-aa0ee9043831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plant: 1210 ( DDE - Plant )'])[1]/following::span[3]</value>
      <webElementGuid>d321e9cd-9dc9-4901-9da5-320d48e2fbbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DDE_DM4MILL_GR_FINAL'])[3]/following::span[6]</value>
      <webElementGuid>83456b33-df84-4e5f-9336-5f1cd285ea99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Focus Search'])[1]/preceding::span[2]</value>
      <webElementGuid>c777db8d-c29f-4014-85d9-a3a0ea037828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::span[5]</value>
      <webElementGuid>9cfd4e24-5a78-46e0-aa6e-8538c6b8e621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>eab609b3-8057-456c-afb1-210cd4775135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'searchFieldInShell-button-inner']</value>
      <webElementGuid>551bd0d5-3fa1-4880-99d6-46332ef6b636</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
