<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Mar 04, 2025, 45102 PM</name>
   <tag></tag>
   <elementGuidId>c8112446-900b-479a-8010-457e066c1eab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__text112-__clone138</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__text112-__clone138']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Mar 04, 2025, 4:51:02 PM&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>637a21f6-06c1-4196-9d3e-934beac4ff8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__text112-__clone138</value>
      <webElementGuid>6e617280-1068-438f-8514-1de10f5e43d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__text112-__clone138</value>
      <webElementGuid>d0eea7b6-e322-4066-a285-53ca64fb9134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>2b6340ad-4aad-4f05-a339-f6ade5f04868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapUiSelectable sapMTextMaxWidth</value>
      <webElementGuid>38ef3143-e596-48df-a616-9c449f5c124a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mar 04, 2025, 4:51:02 PM</value>
      <webElementGuid>23b0b91e-e578-4a08-b513-a9269b217be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__text112-__clone138&quot;)</value>
      <webElementGuid>0c8ce0b4-7876-4525-b601-8f58d3a39c35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__text112-__clone138']</value>
      <webElementGuid>398eb1fa-1bee-40d0-9f9b-c873811e8b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='__item80-__clone138-cell0']/span</value>
      <webElementGuid>7a78f1e4-a138-4370-9843-a22d8a5d79a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comments'])[1]/following::span[1]</value>
      <webElementGuid>e92e1d26-d780-4841-8d1c-97379f4a23a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sfc'])[1]/following::span[2]</value>
      <webElementGuid>a8085c23-dd4a-4377-8d64-80241644e75f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DDE-101-0500-2500'])[3]/preceding::span[3]</value>
      <webElementGuid>284986d7-5c6f-4e03-a7ee-20f4a405a753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mar 04, 2025, 4:36:17 PM'])[1]/preceding::span[9]</value>
      <webElementGuid>82e9cfdb-4053-4db2-a96f-5e1bc88bc2f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mar 04, 2025, 4:51:02 PM']/parent::*</value>
      <webElementGuid>16aefaed-b21f-48be-9240-48d8d4cdf787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr/td[2]/span</value>
      <webElementGuid>225ca53f-e8d2-4998-b737-d5153c893de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__text112-__clone138' and (text() = 'Mar 04, 2025, 4:51:02 PM' or . = 'Mar 04, 2025, 4:51:02 PM')]</value>
      <webElementGuid>5a0b2ead-1839-4f98-8273-8197840aaddb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
