<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Go</name>
   <tag></tag>
   <elementGuidId>b9eb0864-bada-4f47-954f-27eb82f8bc7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--filterBar-btnGo-inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--filterBar-btnGo-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Go&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2ad7ffb3-9826-4bfd-a8fd-a4fa65167ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--filterBar-btnGo-inner</value>
      <webElementGuid>e0a54911-6280-4a83-a739-496edb7956e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMBtnInner sapMBtnHoverable sapMFocusable sapMBtnText sapMBtnEmphasized</value>
      <webElementGuid>77f1caf3-7272-45c5-8122-14106072e31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>d181856b-2d68-4153-97c1-d0a192196967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--filterBar-btnGo-inner&quot;)</value>
      <webElementGuid>b404ceca-6750-43b8-886f-ab61b3d9a81d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--filterBar-btnGo-inner']</value>
      <webElementGuid>67a3ea4d-7d7f-404f-94aa-8df959a98b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--filterBar-btnGo']/span</value>
      <webElementGuid>e266dc97-69e8-44c3-9906-77c33899f8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Planned Start Date Range'])[1]/following::span[3]</value>
      <webElementGuid>40cda0cc-f87f-4e38-adc6-358257784da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SFC Status'])[1]/following::span[9]</value>
      <webElementGuid>e02401bf-9a17-441b-825c-fefbe5cfb8cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/preceding::span[2]</value>
      <webElementGuid>1ca50787-30ce-48e5-9da1-24483d537db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/button/span</value>
      <webElementGuid>bfa3bdaa-3f13-40b9-93da-c45c4d676736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__xmlview100--reservedComponentContainer---orderPodSelectionPlugin--filterBar-btnGo-inner' and (text() = 'Go' or . = 'Go')]</value>
      <webElementGuid>afafbccb-7cf1-4c9c-91d9-7cb521b97ba4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
