<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_4 M</name>
   <tag></tag>
   <elementGuidId>869b9f26-5a77-49bc-beb7-50b5cb1395f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__item80-__clone138-cell4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='__item80-__clone138-cell4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;4 M&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0ad65e6d-2946-48e3-a7bc-c80dda169eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__item80-__clone138-cell4</value>
      <webElementGuid>25b8476d-919a-4837-afbf-c6ddc9f8d32c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>f653f961-e967-49cf-8cda-cb75bca0b51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>31ab916e-7c8c-489b-8866-69cf045278e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-column</name>
      <type>Main</type>
      <value>__column24</value>
      <webElementGuid>e0fc7a5b-ef41-45ce-9158-b1a71a139a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMListTblCell sapMTblCellFocusable</value>
      <webElementGuid>ebe390af-722e-4fc8-8747-b69067ef84f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5a1d2b72-8175-4a21-8fc1-28343a2dee56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4 M</value>
      <webElementGuid>a110f8dc-ed37-4230-a503-0eaeaafb9183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__item80-__clone138-cell4&quot;)</value>
      <webElementGuid>aa345fef-9e88-476c-8c37-6f1653017116</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='__item80-__clone138-cell4']</value>
      <webElementGuid>418a5ac6-b96c-4715-bc0e-86f8d3669ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='__item80-__clone138']/td[6]</value>
      <webElementGuid>f1d1e969-20de-4b63-8767-8a2d8cb1a193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DDE-101-0500-2500'])[3]/following::td[1]</value>
      <webElementGuid>87909ca8-2996-494d-90b4-94fd56d133dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mar 04, 2025, 4:51:02 PM'])[1]/following::td[4]</value>
      <webElementGuid>f7467652-1eb1-4ce1-82ae-efb6b164fc9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mar 04, 2025, 4:36:17 PM'])[1]/preceding::td[7]</value>
      <webElementGuid>ef798c53-8594-4c00-b06a-e348a67e80ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DDE-101-0500-2500'])[4]/preceding::td[10]</value>
      <webElementGuid>0b2bd4f7-74a1-4f8f-8dc1-b9d1bcb81aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr/td[6]</value>
      <webElementGuid>e4a7a5f8-e990-404a-af76-5b79cf2d3e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = '__item80-__clone138-cell4' and (text() = '4 M' or . = '4 M')]</value>
      <webElementGuid>2ba3bc48-5018-472c-ab44-e9bb2614575f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
